namespace AdvantShop.Saas
{
    public enum ESaasProperty
    {
        Name,
        IsWork,
        LeftDay,
        ClientNumber,
        ValidTill,
        Bonus,
        Money,
        Error,
        BalanceFormating,
        SupportChat,
        HaveDomains,

        ProductsCount,
        PhotosCount,
        ManagersCount,
        FileStorageVolume,
        HaveExcel,
        Have1C,
        HaveExportFeeds,
        ExportFeedsAutoUpdate,
        HavePriceRegulating,
        //HaveBankIntegration,              
        HaveCrm,
        HaveTelephony,
        HaveMobileAdmin,
        HaveTags,
        HaveCustomerLog,
        HaveCustom,
        HaveVIPsupport,
        MobileVersion,
        GoogleYandexMetriks,
        LandingPage,
        RoleActions,
        OrderStatuses,
        OrderAdditionFields,
        BonusSystem,
        DeepAnalytics,
        BizProcess,

        EmployeesCount,
        CustomerAdditionFields,
        //HaveCrmSalesFunnels,
        LeadsListsCount,
        HavePriceVisibility,
        CRMIntegrationsCount,
        HaveCustomerSegmets,
        DomainMaxAmount,

        LandingFunnelCount,
        LandingFunnelPageCount,

        HaveTriggers,
        TriggersCount,
        HaveLandingFunnel,
        HaveBooking,
        HaveTasks,
        
        Vk,
        Reseller,
        Instagram,
        Facebook,
        Ok,
        Telegram,
        Partners,

        LandingPage_AvailableFrom,
        Triggers_AvailableFrom,
        ExportFeeds_AvailableFrom,
        Vk_AvailableFrom,
        BonusSystem_AvailableFrom,
        Partners_AvailableFrom,
        Reseller_AvailableFrom,
        Instagram_AvailableFrom,
        Facebook_AvailableFrom,
        Ok_AvailableFrom,
        Telegram_AvailableFrom,

        HaveMobileApp,
        CustomCSS,

        MoneyService,
        BonusService,
        BalanceServiceFormating,
        EmailsReains,
        SearchRemains,
        AllServicesRemainsFormated,


        CheckMailingSendTo,
    }
}