INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Tasks.AddTask.NoManager','Постановщик задачи должен быть менеджером')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Tasks.AddTask.NoManager','Task manager was not found')

GO--

UPDATE [CMS].[StaticBlock]
   SET [Content] = '<div class="closed-store">
					<div class="closed-store__container">
					<div class="closed-store__title">Ведутся технические работы.</div>
					<div class="closed-store__content">Скоро мы откроемся.</div>
					</div>
					</div>'
      ,[Modified] = GetDate()
	Where [Key] = 'store_closed' and [Modified] = '2015-04-06 12:04:35.143'
	
GO--

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.MainPageModeHint', 'Режим отображения главной страницы <br/>Структура сайта может быть представлена в двухколоночном и одноколоночном режиме.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/template-settings#11" target="_blank">https://www.advantshop.net/help/pages/template-settings#11</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.MainPageModeHint', 'Homepage display mode <br/>The site structure can be presented in two-column and single-column mode.<br/><br/>  Instruction:<br/> <a href="https://www.advantshop.net/help/pages/template-settings#11" target="_blank">https://www.advantshop.net/help/pages/template-settings#11</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SearchBlockLocationHint', 'Расположение поиска<br/>Данная настройка отвечает за то, в какой области на сайте будет отображаться окно поиска.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/template-settings#13" target="_blank">https://www.advantshop.net/help/pages/template-settings#13</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SearchBlockLocationHint', 'Search Location<br/>This setting is responsible for the area in which the search box will be displayed on the site.<br/><br/>  Instruction:<br/> <a href="https://www.advantshop.net/help/pages/template-settings#13" target="_blank">https://www.advantshop.net/help/pages/template-settings#13</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.RecentlyViewVisibilityHint', 'Вы уже смотрели<br/>Настройка позволяет отображать список товаров, которые клиенты просматривали ранее на сайте<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/template-settings#6" target="_blank">https://www.advantshop.net/help/pages/template-settings#6</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.RecentlyViewVisibilityHint', 'You already watched<br/>The setting allows you to display a list of products that customers viewed previously on the site.<br/><br/>  Instruction:<br/> <a href="https://www.advantshop.net/help/pages/template-settings#6" target="_blank">https://www.advantshop.net/help/pages/template-settings#6</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.WishListVisibilityHint', 'Список желаний<br/>Активность данной настройки позволяет клиентам добавлять товары в свой список желаний.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/template-settings#6" target="_blank">https://www.advantshop.net/help/pages/template-settings#6</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.WishListVisibilityHint', 'A wish list<br/>The activity of this setting allows customers to add products to their wish list.<br/><br/>  Instruction:<br/> <a href="https://www.advantshop.net/help/pages/template-settings#6" target="_blank">https://www.advantshop.net/help/pages/template-settings#6</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.SystemSettings.ShowCookiesPolicyMessageNote', 'Показывать уведомление об использовании cookies<br/>Настройка позволяет выводить для всех посетителей сайта всплывающее окно с уведомлением о том, что для функционирования сайта Вы осуществляете сбор данных пользователя (cookie, данные об IP-адресе и местоположении) в соответствии с законом 152-ФЗ.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/152-fz" target="_blank">https://www.advantshop.net/help/pages/152-fz</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.SystemSettings.ShowCookiesPolicyMessageNote', 'Show cookie notification<br/>The setting allows you to display a pop-up window for all site visitors with a notification that for the operation of the site you are collecting user data (cookies, IP address and location data) in accordance with Law 152-FZ.<br/>  Instruction:<br/> <a href="https://www.advantshop.net/help/pages/152-fz" target="_blank">https://www.advantshop.net/help/pages/152-fz</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.SystemSettings.SiteLanguageNote', 'Язык магазина<br/>Настройка позволяет сменить язык магазина (меняются кнопки, панель администрирования, товары останутся на том языке, на котором заполняли магазин).<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/change-buttons#4" target="_blank">https://www.advantshop.net/help/pages/change-buttons#4</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.SystemSettings.SiteLanguageNote', 'Site language<br/>The setting allows you to change the language of the store (buttons, admin panel change, the products will remain in the language in which the store was filled).<br/><br/>  Instruction:<br/> <a href="https://www.advantshop.net/help/pages/change-buttons#4" target="_blank">https://www.advantshop.net/help/pages/change-buttons#4</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.SettingsCatalog.CatalogCommon.CountCategoriesInLineNote', 'Количество категорий в строке<br/>В данном поле укажите какое количество категорий необходимо выводить в каталоге в одной строке.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/template-settings#4" target="_blank">https://www.advantshop.net/help/pages/template-settings#4</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.SettingsCatalog.CatalogCommon.CountCategoriesInLineNote', 'The number of categories per line<br/>In this field, specify how many categories should be displayed in the catalog on one line.<br/><br/>  Instruction:<br/> <a href="https://www.advantshop.net/help/pages/template-settings#4" target="_blank">https://www.advantshop.net/help/pages/template-settings#4</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.SettingsCatalog.CatalogCommon.ShowQuickViewNote', 'Быстрый просмотр<br/>Данная настройка позволяет просмотреть кратко карточку товара не переходя во внутрь')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.SettingsCatalog.CatalogCommon.ShowQuickViewNote', 'Quick view<br/>This setting allows you to view briefly the product card without going inside')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.CountCatalogProductInLineNote', 'Количество товаров в строке<br/>Данная настройка позволяет выставить необходимое количество товаров отображающихся в одной строке в категории.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/template-settings#5" target="_blank">https://www.advantshop.net/help/pages/template-settings#5</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.CountCatalogProductInLineNote', 'Number of products per line<br/>This setting allows you to set the required number of products displayed on one line in the category.<br/><br/> Instruction:<br/> <a href="https://www.advantshop.net/help/pages/template-settings#5" target="_blank">https://www.advantshop.net/help/pages/template-settings#5</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Catalog.SetAllProductsManualRatioNote', ' Рейтинг<br/>В данном поле пишите рейтинг, который можно установить массово для всех товаров. Значения указываются от 1 до 5. <br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/catalog-view#10" target="_blank">https://www.advantshop.net/help/pages/catalog-view#10</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Catalog.SetAllProductsManualRatioNote', ' Rating<br/>In this field, write a rating that can be set in bulk for all products.Values ​​are from 1 to 5<br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/catalog-view#10" target="_blank">https://www.advantshop.net/help/pages/catalog-view#10</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.SettingsCatalog.CatalogCommon.ShowFilterNote', 'Показывать фильтр в каталоге <br/>Настройка позволяет вывести фильтр со свойствами в каталог. Другими словами настройка включает работу фильтра в магазине.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/catalog-filtr#5" target="_blank">https://www.advantshop.net/help/pages/catalog-filtr#5 </a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.SettingsCatalog.CatalogCommon.ShowFilterNote', 'Show filter in catalog <br/>Setting allows you to display a filter with properties in a directory. In other words, the setting includes the filter in the store. <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/catalog-filtr#5" target="_blank">https://www.advantshop.net/help/pages/catalog-filtr#5 </a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.SettingsCatalog.CatalogCommon.ResizeGoodsPicturesNote', 'Пережать фотографии товаров <br/>Функция пережатия позволяет изменять размеры изображений для ранее загруженных фотографий на сайт. <br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/photo-product#2" target="_blank">https://www.advantshop.net/help/pages/photo-product#2</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.SettingsCatalog.CatalogCommon.ResizeGoodsPicturesNote', 'Resize goods pictures <br/>The compression function allows you to resize images for previously uploaded photos to the site. <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/photo-product#2" target="_blank">https://www.advantshop.net/help/pages/photo-product#2</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.BrandsPerPageHote', 'Количество производителей на странице<br/>В поле пишите то количество, которое требуется для отображения на одной страниц.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/brand#4" target="_blank">https://www.advantshop.net/help/pages/brand#4</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.BrandsPerPageHote', 'Number of manufacturers per page<br/>In the field, write the amount that is required to display on one page. <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/brand#4" target="_blank">https://www.advantshop.net/help/pages/brand#4</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.ShowProductsInBrandHote', 'Выводить список товаров<br/>Настройка позволяет выводить на странице бренда список товаров данного бренда <br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/brand#4" target="_blank">https://www.advantshop.net/help/pages/brand#4</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.ShowProductsInBrandHote', 'Display a list of products<br/>The setting allows you to display on the brand page a list of products of this brand <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/brand#4" target="_blank">https://www.advantshop.net/help/pages/brand#4</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.ShowCategoryTreeInBrandHote', 'Выводить дерево категорий<br/>Настройка позволяет на странице бренда отображать категории, в которых имеются товары данного бренда <br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/brand#4" target="_blank">https://www.advantshop.net/help/pages/brand#4</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.ShowCategoryTreeInBrandHote', 'Display category tree<br/>The setting allows you to display on the brand page the categories in which the goods of this brand <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/brand#4" target="_blank">https://www.advantshop.net/help/pages/brand#4</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.BrandLogoHote', 'Размеры изображения отзыва<br/>Максимальные размеры изображений производителей(в пикселях)')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.BrandLogoHote', 'Review image sizes <br/> Maximum producer image sizes (in pixels)')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.NewsImageHote', 'Изображение новости<br/>Максимальные размеры изображений новостей (в пикселях)<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/add-news" target="_blank">https://www.advantshop.net/help/pages/add-news</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.NewsImageHote', 'News Image<br/>Maximum sizes of news images (in pixels) <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/add-news" target="_blank">https://www.advantshop.net/help/pages/add-news</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.News.MainPageTextNote', 'Текст заголовка подписки на новости<br/>Указываете текст, который будет отображаться в качестве заголовка в блоке подписки на новости <br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/add-news#3" target="_blank">https://www.advantshop.net/help/pages/add-news#3</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.News.MainPageTextNote', 'Newsletter Header Text<br/>Specify the text that will be displayed as the title in the newsletter subscription block <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/add-news#3" target="_blank">https://www.advantshop.net/help/pages/add-news#3</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.News.NewsPerPageNote', 'Новостей на страницу<br/>В данной настройке указываете число - количество новостей, которые будут выводится в списке всех новостей.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/add-news" target="_blank">https://www.advantshop.net/help/pages/add-news</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.News.NewsPerPageNote', 'News per page<br/>In this setting, specify the number - the number of news that will be displayed in the list of all news.<br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/add-news" target="_blank">https://www.advantshop.net/help/pages/add-news</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.News.NewsMainPageCountNote', 'Новостей на главной<br/>Впишите число - количество новостей отображаемых на главной странице.<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/add-news" target="_blank">https://www.advantshop.net/help/pages/add-news</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.News.NewsMainPageCountNote', 'News on the main<br/>Enter the number - the number of news displayed on the main page. <br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/add-news" target="_blank">https://www.advantshop.net/help/pages/add-news</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowCommunicationWidget.HelpText', 'Показывать виджет коммуникаций<br/>Настройка включает отображение виджетов коммуникаций<br/><br/> Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowCommunicationWidget.HelpText', 'Show communications widget<br/>Customization enables the display of communication widgets<br/><br/> Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowVkontakte.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать ВКонтакте") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowVkontakte.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show VKontakte" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowFaceBook.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать Facebook") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowFaceBook.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show Facebook" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowJivosite.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать JivoSite") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowJivosite.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show JivoSite" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowCallback.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать Callback") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowCallback.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show Callback" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowWhatsApp.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать WhatsApp") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowWhatsApp.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show WhatsApp" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowViber.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать Viber") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowViber.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show Viber" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowOdnoklassniki.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать Одноклассники") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowOdnoklassniki.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show Odnoklassniki" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.ShowTelegram.HelpText', 'Виджеты коммуникаций <br/>1) Активируйте виджет коммуникаций - поставьте галочку в поле "Показывать виджет коммуникаций" <br/>2) Активируйте виджеты, которые планируете выводить (для этого поставьте галочки в полях "Показывать Telegram") <br/>3) И подкючите виджеты согласно инструкциям, подробнее:<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.ShowTelegram.HelpText', 'Communication Widgets<br/>1) Activate the communications widget - check the box "Show communications widget"<br/>2) Activate the widgets that you plan to display (to do this, check the "Show Telegram" boxes)<br/> 3) And connect widgets according to the instructions, more details:<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii</a>')

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Admin.Settings.Template.SocialWidget.CustomWidgetTitleNote', 'Свой виджет<br/>Можно подключить доплнительно каналы связи, которых нет в списке<br/><br/>Инструкция:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii#a9" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii#a9</a>')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Admin.Settings.Template.SocialWidget.CustomWidgetTitleNote', 'Custom widget<br/>You can connect additional communication channels that are not listed<br/><br/>Instruction:<br/><a href="https://www.advantshop.net/help/pages/vidzhety-kommunikatsii#a9" target="_blank">https://www.advantshop.net/help/pages/vidzhety-kommunikatsii#a9</a>')

GO--

Insert Into [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) Values (1, 'Core.Orders.Order.TotalLength', 'Общие габариты (Длина)')
Insert Into [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) Values (2, 'Core.Orders.Order.TotalLength', 'Total demensions (Length)')
Insert Into [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) Values (1, 'Core.Orders.Order.TotalWidth', 'Общие габариты (Ширина)')
Insert Into [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) Values (2, 'Core.Orders.Order.TotalWidth', 'Total demensions (Width)')
Insert Into [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) Values (1, 'Core.Orders.Order.TotalHeight', 'Общие габариты (Высота)')
Insert Into [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) Values (2, 'Core.Orders.Order.TotalHeight', 'Total demensions (Height)')

GO--

INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (1,'Core.Crm.Task.Observer','Наблюдатель')
INSERT INTO [Settings].[Localization] ([LanguageId],[ResourceKey],[ResourceValue]) VALUES (2,'Core.Crm.Task.Observer','Observer')

GO--


ALTER TABLE CRM.TriggerAction ADD
	RequestParamsType int NULL,
	RequestParamsJson nvarchar(MAX) NULL
GO--

if (select count(*) from settings.settings where name = 'SettingsCD.SkipCongratulationsDashboard' )= 0
begin
insert into settings.settings (name, value) values ('SettingsCD.SkipCongratulationsDashboard', 'True')
End

GO--

UPDATE [Settings].[InternalSettings] SET [settingValue] = '8.5.4' WHERE [settingKey] = 'db_version'