using System.Collections.Generic;
using AdvantShop.Core.Services.ChangeHistories;
using AdvantShop.Core.Services.Crm;
using AdvantShop.Core.Services.Crm.BusinessProcesses;
using AdvantShop.Core.Services.Crm.SalesFunnels;
using AdvantShop.Customers;
using AdvantShop.Web.Admin.Models.Tasks;

namespace AdvantShop.Web.Admin.Handlers.BizProcesses
{
    public class BizProcessLeadHandler<TRule> : BizProcessHandler<TRule> where TRule : BizProcessLeadRule
    {
        private readonly Lead _lead;

        public BizProcessLeadHandler(List<TRule> rules, Lead lead) : base(rules, lead)
        {
            _lead = lead;
        }

        public override TaskModel GenerateTask()
        {
            TaskModel = new TaskModel
            {
                LeadId = _lead.Id
            };

            return base.GenerateTask();
        }

        public override void ProcessBizObject()
        {
            if (!_lead.ManagerId.HasValue && Employee != null && SalesFunnelService.CheckAccess(_lead.SalesFunnelId, CustomerService.GetCustomer(Employee.CustomerId)))
            {
                _lead.ManagerId = Employee.AssociatedManagerId;
                LeadService.UpdateLead(_lead, updateCustomer: false, changedBy: new ChangedBy("autogenerated task"));
            }
        }
    }


}
